### ISSUE TITLE
Electron Fundamentals bug on Windows

### ISSUE THREAD

**Issue by RHMason** [jaketrent/jaketrent-blog#11]
Jake,

Really liking your course but ran across a stubborn bug tonight with the loadURL in main.js.  Absolutely not working on Windows 7, nor I think on Windows at all.

Found the solution in the last comment by Harmandeep-Singh here:
https://github.com/electron/electron-quick-start/issues/18

Here's a working version of the line:

mainWindow.loadURL('file://' + __dirname + '/index.html')

Note that this is a bug the Electron people have known about for nine months!  They're not showing a lot of love for Windows developers ;<(.

Rick

**Comment by jaketrent** [comment]
@RHMason Well that stinks.  This is really interesting.  I wonder why the `string interpolation` doesn't seem to work on Windows.  Seems really odd given that the output should be same string and that the syntax support seems very internal to Node -- which again, I would think would work the same across OSes.  

That is a stubborn bug.  

Given that this fix works for you, and I don't mind making the change for everyone in the exercise files, I'll upload some new exercise files with the change, and Windows users should have better luck.  Thanks for the heads up!

**Comment by jaketrent** [comment]
@RHMason Sorry, I think I'm going to back track a little here...  I'm looking at the discussion tab on the course.  It looks like someone else tried to write the line in question.  They used single quotes like this:

```
mainWindow.loadURL('file://${__dirname}/countdown.html')
```

When the should have used back ticks:

```
mainWindow.loadURL(`file://${__dirname}/countdown.html`)
```

It looks like you have probably made the same mistake based on your comment and my closer inspection of the code in the bug you referenced.  Note that the bug is closed (essentially as a "will not fix/no problem") and the person who filed that report also used single quotes instead of back ticks.

Here's some additional info on this es6 feature of string interpolation or "template literals":
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by RHMason** [comment]
Jake,

Thanks for pointing me in the right direction, I've now got your original
code working.  I've been a programmer for 30 years and I've never known
about back ticks.  Are they used just on URL related code in Electron?

You may want to add a yellow note to the video where back ticks are used,
on my laptop screen they're can't be distinguished from single quotes.

Rick

**Comment by jaketrent** [comment]
Hey @RHMason .  Back ticks are used much more generally in ES6.  It's a feature used for string interpolation in generally.  Definitely not *just* for URL-related or Electron-related code.

Thanks for the suggestion.
